"""add year column

Revision ID: 2e4f76673579
Revises: 93d13289e59d
Create Date: 2025-06-26 20:36:42.914511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4f76673579'
down_revision = '93d13289e59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
