"""empty message

Revision ID: 9230c9add406
Revises: 
Create Date: 2025-06-26 20:32:41.532122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9230c9add406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_make', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.drop_column('car_make')

    # ### end Alembic commands ###
