"""add car_model column

Revision ID: 93d13289e59d
Revises: 9230c9add406
Create Date: 2025-06-26 20:35:01.586887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d13289e59d'
down_revision = '9230c9add406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.drop_column('car_model')

    # ### end Alembic commands ###
