"""Add departure and return dates to TravelInsuranceRequest

Revision ID: a4ab56f5ed71
Revises: e1e20c94ef9a
Create Date: 2025-07-06 19:38:00.107279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ab56f5ed71'
down_revision = 'e1e20c94ef9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.drop_column('car_model')
        batch_op.drop_column('car_make')
        batch_op.drop_column('year')

    with op.batch_alter_table('travel_insurance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_insurance_request', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('departure_date')

    with op.batch_alter_table('auto_insurance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('car_make', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('car_model', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
